<?php

use Illuminate\Database\Seeder;

// @codingStandardsIgnoreLine
class CandidateTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('candidates')->insert([
            [
                'name' => 'Nguyễn văn Đức',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 1,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn Chung',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 2,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn Xuân Trường',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 3,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn Tiến Đức',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 4,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn Phúc Triệu',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 5,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Bùi Quang Khánh',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 6,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Bùi Quang Linh',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 7,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn Chí Diện',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 8,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'php'
            ],
            [
                'name' => 'Nguyễn Văn Tiến',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 9,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'react'
            ],
            [
                'name' => 'Nguyễn văn Đức',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 10,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'react'
            ],
            [
                'name' => 'Nguyễn văn tuấn',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 11,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'php'
            ],
            [
                'name' => 'Nguyễn Tuấn Mạnh',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 12,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn Đức',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 13,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn Văn B',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 14,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'PHP'
            ],
            [
                'name' => 'Nguyễn văn Đức',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 15,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'PHP'
            ],
            [
                'name' => 'Trấn Văn Trường',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 16,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'php'
            ],
            [
                'name' => 'Nguyễn văn Đức',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 17,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn a',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 18,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn v',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 19,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn c',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 20,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn s',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 21,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn h',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 22,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn h',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 23,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn r',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 24,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn r ',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 25,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn d',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 26,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn x',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 27,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn Z',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 28,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn K',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 29,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn L',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 30,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn O',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 31,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn Q',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 32,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'php'
            ],
            [
                'name' => 'Nguyễn văn Q',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 33,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
            [
                'name' => 'Nguyễn văn T',
                'nationality' => 'china',
                'gender' => 'nam',
                'DoB' => '2000-01-01',
                'current_add' => 'hn',
                'request' => 'lương cao',
                'exp' => '3 năm kinh nghiêm',
                'location' => 'HN',
                'user_id' => 1,
                'image'=> 'https://www.freepik.com/free-photo/man-full-manager-trendy-career_1013658.htm#page=2&query=candidate&position=5',
                'job'=> 'java'
            ],
        ]);
    }
}
